### ISSUE TITLE
Firefox Awesomebar updated, but not icon on tab

### ISSUE THREAD

**Issue by tomByrer** [tommoor/tinycon#25]
For my WinXPsp3 Firefox nightly 13.0a1 (2012-03-12), the icon next to the URL updates just fine, but the icon in the tab reverts to a folder.  In fairness, same issue with Notificon.  Let me know if you need a screenshot.
cheers!

**Comment by tommoor** [comment]
I'm tidying up this repository and closing issues over a year old, thanks for the report and please reopen if you'd still like to see this fixed.
