### ISSUE TITLE
Force use of favicon.ico only?

### ISSUE THREAD

**Issue by cantonweb** [tommoor/tinycon#44]
Is there a way to force (or edit) the script to make it use only the favicon.ico image rather than the Apple Touch logo image?  The problem is that in Chrome, the rendering of the Touch logo is very ragged looking, where the favicon version is smooth and aliased properly.  I could easily tell which image it was grabbing since we changed our Touch logo on one site, and not the favicon, and our "admin" area showed the proper smooth icon in the browser tab as opposed to the ragged version processed through Tinycon on the public side.

**Comment by tommoor** [comment]
I'm tidying up this repository and closing issues over a year old, thanks for the report and please reopen if you'd still like to see this fixed.
