### ISSUE TITLE
Request: Add bower.json to the repo

### ISSUE THREAD

**Issue by ssokolow** [tommoor/tinycon#83]
I have a Python project where I'm using [Bower](http://bower.io/docs/creating-packages/) to manage the client-side JS dependencies (a choice made based on what was offered for various dependencies I wanted).

Would you mind adding a `bower.json` to this so I can use the GitHub URLs as valid arguments to `bower install`?

**Comment by tommoor** [comment]
I'm not a bower user, but if you submit a PR with the bower file I'll happily accept!

**Comment by ssokolow** [comment]
It may have to wait until May. I'm behind on some deadlines, so this specific project's Tinycon dependency has been deferred.

(I just didn't want to needlessly put off filing the report. It feels too much like procrastination.)

**Comment by simison** [comment]
Here ya go: https://github.com/tommoor/tinycon/pull/84

Thanks for the library. It's very handy (and tiny!)

**Comment by tommoor** [comment]
closed by https://github.com/tommoor/tinycon/pull/84
