### ISSUE TITLE
Do not assume <link> tags are all in <head>

### ISSUE THREAD

**Issue by dvdplm** [tommoor/tinycon#90]
Ran into a strange issue today on a site with unusual markup. They have their <link> tag with the favicon in the <body> tag (don't ask me why!) which causes Tinycon to fail in `removeFaviconTag()` at load because it is trying to remove a link-node that is not a child of `head`.
The fix is fairly straight forward: https://github.com/dvdplm/tinycon/commit/7e8b2078680b7967d1f43ac6cdcfaaceb92d5b44

**Comment by tommoor** [comment]
Hey @dvdplm - makes sense, want to put in a PR?

**Comment by dvdplm** [comment]
@tommoor will do. (Our fork has diverged a little but will redo against master)

**Comment by tommoor** [comment]
closed by 3a60dfea4c9f218bcb18096d6821a1ccaf495b74
